import { CommunityPost, Helpline, SafetyLocation, IncidentReport } from './types';

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: '1',
    authorName: 'Priya S.',
    incidentType: 'Eve-teasing',
    location: 'Koramangala, Bangalore',
    timeAgo: '10 mins ago',
    description: 'Experienced harassment near the metro station. Please be careful in this area, especially after 8 PM.',
    isAnonymous: false,
    upvotes: 12,
    comments: 3,
  },
  {
    id: '2',
    authorName: 'Anonymous',
    incidentType: 'Stalking',
    location: 'Bandra West, Mumbai',
    timeAgo: '1 hour ago',
    description: 'Someone has been following me for the past few days. Reported to police.',
    isAnonymous: true,
    upvotes: 8,
    comments: 5,
  },
  {
    id: '3',
    authorName: 'Kavya R.',
    incidentType: 'Harassment',
    location: 'Connaught Place, Delhi',
    timeAgo: '2 hours ago',
    description: 'Inappropriate comments by shopkeeper. Avoided the store and reported the incident.',
    isAnonymous: false,
    upvotes: 15,
    comments: 7,
  },
  {
    id: '4',
    authorName: 'Anonymous',
    incidentType: 'Other',
    location: 'Anna Nagar, Chennai',
    timeAgo: '4 hours ago',
    description: 'Felt unsafe walking alone at night. Good lighting needed in this area.',
    isAnonymous: true,
    upvotes: 6,
    comments: 2,
  },
  {
    id: '5',
    authorName: 'Ananya K.',
    incidentType: 'Eve-teasing',
    location: 'Hitech City, Hyderabad',
    timeAgo: '6 hours ago',
    description: 'Bike riders making inappropriate gestures. Be cautious on this route.',
    isAnonymous: false,
    upvotes: 9,
    comments: 4,
  },
];

export const mockHelplines: Helpline[] = [
  {
    id: '1',
    name: 'Women Helpline (National)',
    number: '1091',
    category: 'women-helpline',
    available247: true,
    languages: ['en', 'hi', 'ta', 'te', 'kn'],
  },
  {
    id: '2',
    name: 'Police Emergency',
    number: '100',
    category: 'police',
    available247: true,
    languages: ['en', 'hi', 'ta', 'te', 'kn'],
  },
  {
    id: '3',
    name: 'Medical Emergency',
    number: '108',
    category: 'emergency',
    available247: true,
    languages: ['en', 'hi', 'ta', 'te', 'kn'],
  },
  {
    id: '4',
    name: 'Domestic Violence Helpline',
    number: '181',
    category: 'domestic-violence',
    available247: true,
    languages: ['en', 'hi', 'ta', 'te', 'kn'],
  },
  {
    id: '5',
    name: 'Mental Health Support',
    number: '9152987821',
    category: 'mental-health',
    available247: false,
    languages: ['en', 'hi'],
  },
  {
    id: '6',
    name: 'Bangalore Women Safety',
    number: '080-22943225',
    category: 'women-helpline',
    available247: false,
    languages: ['en', 'kn', 'hi'],
  },
  {
    id: '7',
    name: 'Mumbai Women Helpline',
    number: '022-24125054',
    category: 'women-helpline',
    available247: false,
    languages: ['en', 'hi'],
  },
  {
    id: '8',
    name: 'Delhi Women Helpline',
    number: '011-23379271',
    category: 'women-helpline',
    available247: false,
    languages: ['en', 'hi'],
  },
];

export const mockSafetyLocations: SafetyLocation[] = [
  {
    id: '1',
    lat: 12.9716,
    lng: 77.5946,
    type: 'safe',
    name: 'MG Road Metro Station',
    description: 'Well-lit area with security cameras and police presence',
  },
  {
    id: '2',
    lat: 12.9698,
    lng: 77.5926,
    type: 'risky',
    name: 'Dark Alley near Commercial Street',
    description: 'Poorly lit, avoid after sunset',
  },
  {
    id: '3',
    lat: 12.9352,
    lng: 77.6245,
    type: 'safe',
    name: 'Koramangala Police Station',
    description: 'Police station - safe zone',
  },
  {
    id: '4',
    lat: 19.0760,
    lng: 72.8777,
    type: 'safe',
    name: 'Bandra Station',
    description: 'Busy area with good security',
  },
  {
    id: '5',
    lat: 19.0596,
    lng: 72.8295,
    type: 'risky',
    name: 'Isolated area near Mahim Creek',
    description: 'Secluded area, avoid during late hours',
  },
  {
    id: '6',
    lat: 28.6139,
    lng: 77.2090,
    type: 'safe',
    name: 'Connaught Place Central Park',
    description: 'Central location with good foot traffic',
  },
  {
    id: '7',
    lat: 13.0827,
    lng: 80.2707,
    type: 'safe',
    name: 'Marina Beach Main Area',
    description: 'Popular tourist spot with police patrol',
  },
  {
    id: '8',
    lat: 17.4065,
    lng: 78.4772,
    type: 'risky',
    name: 'Secluded area in Old City',
    description: 'Narrow lanes, minimal lighting',
  },
];

export const mockIncidentReports: IncidentReport[] = [
  {
    id: '1',
    type: 'eve-teasing',
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: 'MG Road, Bangalore',
    },
    timestamp: new Date('2024-01-15T18:30:00Z'),
    description: 'Group of men making inappropriate comments',
    isAnonymous: false,
    reporterId: '1',
    status: 'pending',
  },
  {
    id: '2',
    type: 'harassment',
    location: {
      lat: 19.0760,
      lng: 72.8777,
      address: 'Bandra West, Mumbai',
    },
    timestamp: new Date('2024-01-15T16:45:00Z'),
    description: 'Inappropriate touching in crowded area',
    isAnonymous: true,
    status: 'verified',
  },
  {
    id: '3',
    type: 'stalking',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, Delhi',
    },
    timestamp: new Date('2024-01-15T14:20:00Z'),
    description: 'Person following me for several blocks',
    isAnonymous: false,
    reporterId: '2',
    status: 'resolved',
  },
];

// Voice commands in different languages
export const voiceCommands = {
  en: {
    sos: ['help', 'emergency', 'sos', 'danger'],
    safeRoute: ['safe route', 'navigation', 'directions'],
    report: ['report incident', 'report', 'complaint'],
    helpline: ['call helpline', 'emergency number', 'police'],
  },
  hi: {
    sos: ['मदद', 'आपातकाल', 'खतरा'],
    safeRoute: ['सुरक्षित रास्ता', 'नेवीगेशन', 'दिशा'],
    report: ['शिकायत दर्ज करें', 'रिपोर्ट', 'शिकायत'],
    helpline: ['हेल्पलाइन कॉल करें', 'आपातकालीन नंबर', 'पुलिस'],
  },
  kn: {
    sos: ['ಸಹಾಯ', 'ತುರ್ತು', 'ಅಪಾಯ'],
    safeRoute: ['ಸುರಕ್ಷಿತ ಮಾರ್ಗ', 'ನ್ಯಾವಿಗೇಶನ್', 'ದಿಕ್ಕುಗಳು'],
    report: ['ಘಟನೆ ವರದಿ', 'ವರದಿ', 'ದೂರು'],
    helpline: ['ಹೆಲ್ಪ್‌ಲೈನ್ ಕರೆ', 'ತುರ್ತು ಸಂಖ್ಯೆ', 'ಪೊಲೀಸ್'],
  },
  ta: {
    sos: ['உதவி', 'அவசரம்', 'ஆபத்து'],
    safeRoute: ['பாதுகாப்பான வழி', 'வழிசெலுத்தல்', 'திசைகள்'],
    report: ['சம்பவ அறிக்கை', 'அறிக்கை', 'புகார்'],
    helpline: ['உதவி எண் அழை', 'அவசர எண்', 'போலீஸ்'],
  },
  te: {
    sos: ['సహాయం', 'అత్యవ��రం', 'ప్రమాదం'],
    safeRoute: ['సురక్షిత మార్గం', 'నావిగేషన్', 'దిశలు'],
    report: ['సంఘటన నివేదిక', 'నివేదిక', 'ఫిర్యాదు'],
    helpline: ['హెల్ప్‌లైన్ కాల్', 'అత్యవసర నంబర్', 'పోలీస్'],
  },
};
